.TH intersect 1 "13 February 2016" "version 1.0"
.SH NAME
Intersect - A function to read in files and count the number of words that are in all of the files given
.SH SYNOPSIS
.B Intersect
The intersect program takes in any number of files and runs a main check between them.
.SH DESCRIPTION
The intersect program stores words from the first file into a hash table,
it then runs through each other file given and checks for words that are in each file.
.B This file is still in its beginning stages
.SH OPTIONS
.I This file has no current options available, but the future holds many possibilities.
.SH BUGS
.B BUG 1

.I Hash collisions have not been solved in this version of the code!

.B BUG 2

.I This version of the program does not check to see if words are cut off.
.SH AUTHOR
Stephen Paradis, I can be contacted at UMBC Training Centers from 8 a.m to 4 p.m.

.I M-F

.SH SEE ALSO
.B No current programs to view
